# Jekyll configuration for Open SDG platform

# Doing the Quick start? Here are the settings to update during installation:
#
# Replace the baseurl with the name of this repository. For example, if the repository is named
# "my-site-repository", then update the baseurl like so:
# baseurl: "/my-site-repository"
baseurl: "/open-sdg-site-starter"
# In the next few items, replace "open-sdg" with the name of your GitHub
# organization, and "open-sdg-data-starter" with the name of your data repository.
remote_data_prefix: "https://open-sdg.github.io/open-sdg-data-starter"
# URL for the "Edit Data" button on indicators.
data_edit_url: http://prose.io/#open-sdg/open-sdg-data-starter/edit/develop/data/indicator_[id].csv
# URL for the "Edit Metadata" button on indicators.
metadata_edit_url: http://prose.io/#open-sdg/open-sdg-data-starter/edit/develop/meta/[id].md
#
# The list of languages that are translated. The first one is the default.
languages:
  - en
#
# That's enough for the Quick Start! The remaining settings can be configured later.

# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
# Recommended: set this to a particular "release" of Open SDG. For example:
#remote_theme: open-sdg/open-sdg@0.10.0
remote_theme: open-sdg/open-sdg@master

# Replace this title as needed.
title: Indicators For The Sustainable Development Goals
url: ""
data_dir: data
environment: staging

# Automatically create indicator pages, goal pages,
# and some other required pages.
create_indicators:
  layout: indicator
create_goals:
  layout: goal
create_pages: true

analytics:
  ga_prod: ''

# Sticky share buttons (facebook, twitter and email)
#sharethis_property: '5d279253faeee40012f195e1'

# Replace the email addresses below.
email_contacts:
  questions: test@example.com
  suggestions: test@example.com
  functional: test@example.com

# International Support
# Eg name: Australia and adjective: Australian
country:
  name: Australia
  adjective: Australian

# Optionally uncomment and update the settings below to control the frontpage heading and instructions.
#frontpage_heading: Australian data for Sustainable Development Goal indicators
#frontpage_instructions: Click on each goal, or <span id="jump-to-search"><a>search</a></span>, for Australian statistics for Sustainable Development Goal global indicators.

# Optionally set a title/body for the frontpage banner. The defaults below point to a standard
# translation, but feel free to change it as needed.
frontpage_introduction_banner:
  title: frontpage.intro_title
  description: frontpage.intro_body

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Menu
menu:
  # Use these to customise the main navigation.
  - path: /reporting-status
    # The "translation_key" refers to the key in the SDG Translations repository.
    translation_key: menu.reporting_status
  - path: /about
    translation_key: menu.about
  - path: /guidance
    translation_key: menu.guidance
  - path: /faq
    translation_key: menu.faq
  - path: /news
    translation_key: menu.updates

footer_menu:
  - path: mailto:my-email-address@example.com
    translation_key: menu.contact_us
  - path: https://twitter.com/MyTwitterAccount
    translation_key: general.twitter
  - path: https://facebook.com/MyFacebookAccount
    translation_key: general.facebook
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies

# Configure the text (or "translation key") to be used on the
# non-global metadata tab.
non_global_metadata: indicator.national_metadata

# Set a base for all goal image URLs. Note that the full goal image path will be
# the base below, completed with: /[language]/[number].png (eg, /fr/6.png).
goal_image_base: https://open-sdg.github.io/sdg-translations/assets/img/goals

# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

# Exclude some files/folders.
exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE

# Optionally uncomment and update the settings below to control the mapping functionality.
# These are only a few of the possible settings. For more details, see:
# https://open-sdg.readthedocs.io/en/latest/maps/
#map_options:
#  minZoom: 5
#  tileURL: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
#  tileOptions:
#    attribution: 'My map attribution'
#map_layers:
#  - min_zoom: 5
#    max_zoom: 10
#    subfolder: my-geojson-subfolder
#    label: My map layer label (can be a translation key)
